# Generated by Django 2.2 on 2023-03-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devsoc', '0002_auto_20230306_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devsoc.NoticeTopic'),
        ),
        migrations.AddField(
            model_name='noticeimage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devsoc.NoticeTopic'),
        ),
    ]
