# Generated by Django 2.2 on 2023-03-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devsoc', '0004_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devsoc.Portfolio'),
        ),
    ]
